# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
    defaultProviders:
      metrics:
      - prometheus
    extensionProviders:
    - name: "wayease-duolaimall-ext-auth"
      envoyExtAuthzHttp:
        service: "wayease-duolaimall-user-service.wayease-duolaimall.svc.cluster.local"
        port: 8080
        includeHeadersInCheck:
          - "token"
        includeHeadersInResponse:
          - "userId"
          - "userTempId"
        pathPrefix: "/api/auth"
        failureModeAllow: true
        timeout: 2s
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: wayease-istiod
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: wayease-istiod
  name: istio
  namespace: istio-system
