---
apiVersion: v1
kind: Service
metadata:
  name: wayease-duolaimall-product-service
  namespace: wayease-duolaimall
  labels:
    app: wayease-duolaimall-product-service
spec:
  selector:
    app: wayease-duolaimall-product-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayease-duolaimall-product-service-deployment
  namespace: wayease-duolaimall
  labels:
    app: wayease-duolaimall-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayease-duolaimall-product-service
  template:
    metadata:
      name: wayease-duolaimall-product-service-deployment
      labels:
        app: wayease-duolaimall-product-service
    spec:
      serviceAccountName: wayease-duolaimall-serviceaccount
      containers:
        - name: wayease-duolaimall-product-service
          image: yuweiyi/duolaimall-product-service:0.2.5-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config/application-common.yaml
              subPath: application-common.yaml
            - name: dev-config-volume
              mountPath: /app/config/application-dev.yaml
              subPath: application-dev.yaml
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wayease-duolaimall-product-service-dev-secret
                  key: db-password
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wayease-duolaimall-product-service-dev-secret
                  key: minio-password
      volumes:
        - name: common-config-volume
          configMap:
            name: wayease-duolaimall-common-dev-configmap
            items:
              - key: application-common.yaml
                path: application-common.yaml
        - name: dev-config-volume
          configMap:
            name: wayease-duolaimall-product-service-dev-configmap
            items:
              - key: application-dev.yaml
                path: application-dev.yaml
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wayease-duolaimall-product-service-dev-configmap
  namespace: wayease-duolaimall
data:
  application-dev.yaml: |
    spring:
      datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:replication://wayease-mysql-primary.wayease-middleware.svc.cluster.local:3306,wayease-mysql-secondary.wayease-middleware.svc.cluster.local:3306/wayease_duolaimall_product?
          readFromMasterWhenNoSlaves=true&allowMasterDownConnections=true&allowSlaveDownConnections=true&
          connectTimeout=10000&socketTimeout=30000&autoReconnect=true&loadBalanceStrategy=roundRobin&
          cacheResultSetMetadata=true&useSSL=false&useLocalSessionState=true&cachePrepStmts=true&useServerPrepStmts=true&
          characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: ${DB_PASSWORD}
        hikari:
          connection-test-query: SELECT 1
          connection-timeout: 60000
          idle-timeout: 500000
          max-lifetime: 540000
          maximum-pool-size: 12
          minimum-idle: 10
          pool-name: SPHHikariPool
          registerMbeans: true
          logLevel: DEBUG
    minio:
      endpoint-url: http://8.137.62.188:19000
      access-key: admin
      secret-key: ${MINIO_PASSWORD}
      bucket-name: wayease-duolaimall
      file-prefix: wayease-duolaimall-file-
    logging:
      level:
        pers.wayease.duolaimall.product.mapper: debug
---
apiVersion: v1
kind: Secret
metadata:
  name: wayease-duolaimall-product-service-dev-secret
  namespace: wayease-duolaimall
type: Opaque
data:
  db-password: MndzeCNFREM=
  minio-password: MndzeCNFREM=