---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: wayease-duolaimall-istio-gateway
  namespace: wayease-duolaimall
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: wayease-duolaimall-istio-http-route
  namespace: wayease-duolaimall
spec:
  parentRefs:
    - name: wayease-duolaimall-istio-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /email
      backendRefs:
        - name: wayease-duolaimall-email-service
          port: 8080