---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: wayease-duolaimall-istio-gateway
  namespace: wayease-duolaimall
spec:
  selector:
    istio: wayease-istio-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wayease-duolaimall-istio-virtualservice
  namespace: wayease-duolaimall
spec:
  gateways:
    - wayease-duolaimall-istio-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: "/email"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-email-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/index"
        - uri:
            prefix: "/goods"
        - uri:
            prefix: "/admin/product"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-product-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/list"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-search-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/user"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-user-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/cart"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-cart-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/order"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-order-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/pay"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-pay-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/seckill"
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - token
          - Cookie
          - Content-Type
          - userId
          - userTempId
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: wayease-duolaimall-promo-service.wayease-duolaimall.svc.cluster.local
            port:
              number: 8080

#---
#apiVersion: security.istio.io/v1
#kind: AuthorizationPolicy
#metadata:
#  name: wayease-duolaimall-istio-authorizationpolicy
#  namespace: istio-system
#spec:
#  selector:
#    matchLabels:
#      app: wayease-istio-ingressgateway
#  action: CUSTOM
#  provider:
#    name: "wayease-duolaimall-ext-auth"
#  rules:
#    - to:
#        - operation:
#            paths: ["/user/logout"]
