apiVersion: v1
kind: ConfigMap
metadata:
  name: wayease-duolaimall-common-dev-configmap
  namespace: wayease-duolaimall
data:
  application-common.yaml: |
    custom:
      info:
        project: wayease-duolaimall
        author: wayease
        email: yu_weiyi@outlook.com
    spring:
      redis:
        master: redis://wayease-redis-master.wayease-middleware.svc.cluster.local:6379
        replicas: redis://wayease-redis-replicas.wayease-middleware.svc.cluster.local:6379
        password: ${REDIS_PASSWORD}
    logging:
      level:
        org.apache.rocketmq: debug
    mybatis-plus:
    #  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      mapper-locations: classpath:mapper/*Mapper.xml
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    jwt:
      secret-key: ${JWT_SECRET_KEY}
    rocketmq:
      namesrv:
        addr: 8.137.62.188:9876
      producer:
        group: ${spring.application.name}-producer
      consumer:
        group: ${spring.application.name}-consumer
---
apiVersion: v1
kind: Secret
metadata:
  name: wayease-duolaimall-common-dev-secret
  namespace: wayease-duolaimall
type: Opaque
data:
  jwt-secret-key: d2F5ZWFzZS1kdW9sYWltYWxsLWp3dC1zZWNyZXQta2V5LXdoaWNoLXNpemUtbXVzdC1ndC0yNTY=
  redis-password: MndzeCNFREM=
