apiVersion: v1
kind: ConfigMap
metadata:
  name: wayease-duolaimall-common-dev-configmap
  namespace: wayease-duolaimall
data:
  application-common.yaml: |
    custom:
      info:
        project: wayease-duolaimall
        author: wayease
        email: yu_weiyi@outlook.com
    logging:
      level:
        com.mysql.cj.jdbc: debug
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      mapper-locations: classpath:mapper/*Mapper.xml
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    jwt:
      secret-key: ${JWT_SECRET_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: wayease-duolaimall-common-dev-secret
  namespace: wayease-duolaimall
type: Opaque
data:
  jwt-secret-key: d2F5ZWFzZS1kdW9sYWltYWxsLWp3dC1zZWNyZXQta2V5LXdoaWNoLXNpemUtbXVzdC1ndC0yNTY=
