---
apiVersion: v1
kind: Namespace
metadata:
  name: wayease-duolaimall
  labels:
    author: wayease
    project: duolaimall
    kubernetes.io/metadata.name: wayease-duolaimall
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wayease-duolaimall-serviceaccount
  namespace: wayease-duolaimall
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wayease-duolaimall-role
  namespace: wayease-duolaimall
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "secrets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "services", "pods", "endpoints" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints", "configmaps" ]
    verbs: [ "get", "list", "watch", "update", "patch", "create" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "create", "get", "delete", "update" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings" ]
    verbs: [ "create", "get", "delete", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wayease-duolaimall-configmap-reader-rolebinding
  namespace: wayease-duolaimall
subjects:
  - kind: ServiceAccount
    name: wayease-duolaimall-serviceaccount
    namespace: wayease-duolaimall
roleRef:
  kind: Role
  name: wayease-duolaimall-role
  apiGroup: rbac.authorization.k8s.io
