---
apiVersion: v1
kind: Service
metadata:
  name: wayease-duolaimall-cart-service
  namespace: wayease-duolaimall
  labels:
    app: wayease-duolaimall-cart-service
spec:
  selector:
    app: wayease-duolaimall-cart-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayease-duolaimall-cart-service-deployment
  namespace: wayease-duolaimall
  labels:
    app: wayease-duolaimall-cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayease-duolaimall-cart-service
  template:
    metadata:
      name: wayease-duolaimall-cart-service-deployment
      labels:
        app: wayease-duolaimall-cart-service
        project: wayease-duolaimall
    spec:
      serviceAccountName: wayease-duolaimall-serviceaccount
      containers:
        - name: wayease-duolaimall-cart-service
          image: yuweiyi/duolaimall-cart-service:0.9.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config/application-common.yaml
              subPath: application-common.yaml
            - name: dev-config-volume
              mountPath: /app/config/application-dev.yaml
              subPath: application-dev.yaml
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wayease-duolaimall-common-dev-secret
                  key: jwt-secret-key
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wayease-duolaimall-common-dev-secret
                  key: redis-password
      volumes:
        - name: common-config-volume
          configMap:
            name: wayease-duolaimall-common-dev-configmap
            items:
              - key: application-common.yaml
                path: application-common.yaml
        - name: dev-config-volume
          configMap:
            name: wayease-duolaimall-cart-service-dev-configmap
            items:
              - key: application-dev.yaml
                path: application-dev.yaml
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wayease-duolaimall-cart-service-dev-configmap
  namespace: wayease-duolaimall
data:
  application-dev.yaml: |
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: wayease-duolaimall-cart-service-dev-secret
#  namespace: wayease-duolaimall
#type: Opaque
#data:
#  redis-password: MndzeCNFREM=